### ISSUE TITLE
Bloody Hogwarts still in application.htm.erb

### ISSUE THREAD

**Issue by James-E-White** [turingschool-examples/cabot-cove-college-b2#6]
Update the application view from Bloody Hogwarts to Cabot-Cove @marchandmd @gabrielcnunez

```html
<!DOCTYPE html>
<html>
  <head>
    <title>BloodyHogwarts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>
```

**Comment by cjsim89** [comment]
Thanks @James-E-White , just fixed!

**Comment by MarchandMD** [comment]
If we found other issues throughout the curriculum, would it be frowned upon to maybe submit a PR? 

We're just looking for ways as a small group to contribute to OS projects....

**Comment by cjsim89** [comment]
@MarchandMD not frowned upon at all! Please do 😄
